//! The live poll Worker: serves the web client, the vote API, and both Durable Objects.
//!
//! | Route | Action |
//! | --- | --- |
//! | `GET /partyline/poll-tally/{id}` | WebSocket upgrade for the tally (Latest) |
//! | `GET /partyline/poll-activity/{id}` | WebSocket upgrade for the activity feed (Log) |
//! | `GET /api/polls/{id}` | The question, the tally, and the activity head |
//! | `POST /api/polls/{id}/vote` | Count a vote and publish the tally and the activity |
//! | `POST /api/polls/{id}/reset` | Reset the poll: zero tally, new activity epoch |
//!
//! The two objects show both ways to build a channel's Durable Object:
//!
//! - `PollObject` embeds the hub by hand. It owns the vote counts and publishes the tally
//!   through its own hub, in the same turn as the count changes.
//! - `ActivityChannel` is generated by `channel_object!`. The Worker publishes to it with
//!   `Publisher`.

use partyline_worker::{Connect, Hub, HubConfig, Publisher, close, decode_segment, reject};
use poll_shared::{
    ACTIVITY_BINDING, ActivityEvent, MAX_VOTER_LEN, OPTIONS, PollActivity, PollSnapshot, PollTally,
    QUESTION, TALLY_BINDING, Tally, Vote,
};
use worker::*;

const DAY_MS: u64 = 24 * 60 * 60 * 1000;

partyline_worker::channel_object! {
    /// The activity feed's Durable Object. A small retention window suits a public demo.
    pub struct ActivityChannel: PollActivity {
        config = HubConfig::default().retain_events(200);
    }
}

/// The tally's Durable Object. It owns the vote counts.
#[durable_object]
pub struct PollObject {
    hub: Hub<PollTally>,
    env: Env,
}

impl PollObject {
    fn sql(&self) -> SqlStorage {
        self.hub.state().storage().sql()
    }

    fn tally(&self) -> Result<Tally> {
        let mut tally = Tally::default();
        for row in self
            .sql()
            .exec("SELECT option, count FROM poll_votes", None)?
            .raw()
        {
            if let [
                SqlStorageValue::Integer(option),
                SqlStorageValue::Integer(count),
            ] = row?.as_slice()
                && let Some(slot) = tally.counts.get_mut(*option as usize)
            {
                *slot = *count as u64;
            }
        }
        Ok(tally)
    }

    fn remember_poll(&self, poll: &str) -> Result<()> {
        self.sql().exec(
            "INSERT INTO poll_meta (id, poll) VALUES (1, ?) ON CONFLICT(id) DO UPDATE SET poll = excluded.poll",
            vec![poll.into()],
        )?;
        Ok(())
    }

    fn poll(&self) -> Result<Option<String>> {
        let row = self
            .sql()
            .exec("SELECT poll FROM poll_meta WHERE id = 1", None)?
            .raw()
            .next()
            .transpose()?;
        Ok(match row.as_deref() {
            Some([SqlStorageValue::String(poll)]) => Some(poll.clone()),
            _ => None,
        })
    }

    async fn vote(&self, poll: &str, option: usize) -> Result<Tally> {
        self.remember_poll(poll)?;
        self.sql().exec(
            "INSERT INTO poll_votes (option, count) VALUES (?, 1) ON CONFLICT(option) DO UPDATE SET count = count + 1",
            vec![(option as i64).into()],
        )?;
        let tally = self.tally()?;
        self.hub.publish(&tally).await?;
        self.schedule_daily_reset().await?;
        Ok(tally)
    }

    /// Zeroes the tally, wipes the activity log with a new epoch, and announces the reset.
    async fn reset(&self, poll: &str) -> Result<()> {
        self.sql().exec("DELETE FROM poll_votes", None)?;
        self.hub.publish(&Tally::default()).await?;
        let activity = Publisher::<PollActivity>::new(&self.env, ACTIVITY_BINDING)?;
        activity.reset(poll).await?;
        activity.publish(poll, &ActivityEvent::PollReset).await?;
        Ok(())
    }

    /// Resets the poll at the next UTC midnight, so the public demo starts fresh each day.
    async fn schedule_daily_reset(&self) -> Result<()> {
        let storage = self.hub.state().storage();
        if storage.get_alarm().await?.is_some() {
            return Ok(());
        }
        let next_midnight = (Date::now().as_millis() / DAY_MS + 1) * DAY_MS;
        let date = js_sys::Date::new(&(next_midnight as f64).into());
        storage.set_alarm(ScheduledTime::new(date)).await
    }
}

fn query_param(url: &Url, name: &str) -> Option<String> {
    url.query_pairs()
        .find(|(key, _)| key == name)
        .map(|(_, value)| value.into_owned())
}

impl DurableObject for PollObject {
    fn new(state: State, env: Env) -> Self {
        let hub = Hub::new(state, HubConfig::default());
        for statement in [
            "CREATE TABLE IF NOT EXISTS poll_votes (option INTEGER PRIMARY KEY, count INTEGER NOT NULL)",
            "CREATE TABLE IF NOT EXISTS poll_meta (id INTEGER PRIMARY KEY CHECK (id = 1), poll TEXT NOT NULL)",
        ] {
            if let Err(e) = hub.state().storage().sql().exec(statement, None) {
                console_error!("creating the poll tables failed: {e}");
            }
        }
        Self { hub, env }
    }

    async fn fetch(&self, mut req: Request) -> Result<Response> {
        let upgrade = req.headers().get("upgrade")?.is_some();
        let url = req.url()?;
        let poll = query_param(&url, "poll").unwrap_or_default();
        match (upgrade, req.method(), url.path()) {
            (false, Method::Post, "/vote") => {
                let vote: Vote = req.json().await?;
                Response::from_json(&self.vote(&poll, vote.option).await?)
            }
            (false, Method::Get, "/tally") => Response::from_json(&self.tally()?),
            (false, Method::Post, "/reset") => {
                self.reset(&poll).await?;
                Response::empty()
            }
            _ => self.hub.fetch(req).await,
        }
    }

    partyline_worker::hub_websocket_handlers!(hub);

    async fn alarm(&self) -> Result<Response> {
        // The daily reset. The hub has no age-based trimming in Latest mode.
        if let Some(poll) = self.poll()? {
            self.reset(&poll).await?;
        }
        self.hub.on_alarm().await
    }
}

fn poll_stub(env: &Env, id: &str) -> Result<Stub> {
    env.durable_object(TALLY_BINDING)?
        .id_from_name(id)?
        .get_stub()
}

async fn call_poll(
    env: &Env,
    id: &str,
    method: Method,
    path: &str,
    body: Option<String>,
) -> Result<Response> {
    let mut init = RequestInit::new();
    init.with_method(method);
    if let Some(body) = body {
        init.with_body(Some(body.into()));
    }
    let mut url = Url::parse("https://poll")?;
    url.set_path(path);
    url.query_pairs_mut().append_pair("poll", id);
    let req = Request::new_with_init(url.as_str(), &init)?;
    poll_stub(env, id)?.fetch_with_request(req).await
}

fn client_ip(req: &Request) -> String {
    req.headers()
        .get("cf-connecting-ip")
        .ok()
        .flatten()
        .unwrap_or_else(|| "local".to_owned())
}

/// The `{id}` route parameter, percent-decoded. Routers hand it out still encoded, and the
/// client encodes the ID, so `Connect` and `Publisher` must both use the decoded form.
fn route_id<D>(ctx: &RouteContext<D>) -> Option<String> {
    ctx.param("id").and_then(|id| decode_segment(id))
}

#[event(fetch)]
async fn fetch(req: Request, env: Env, _ctx: Context) -> Result<Response> {
    Router::new()
        .get_async("/partyline/poll-tally/:id", |req, ctx| async move {
            let Some(id) = route_id(&ctx) else {
                return reject(close::BAD_REQUEST, "invalid id");
            };
            Connect::<PollTally>::new(id)
                .forward(&ctx.env, TALLY_BINDING, req)
                .await
        })
        .get_async("/partyline/poll-activity/:id", |req, ctx| async move {
            let Some(id) = route_id(&ctx) else {
                return reject(close::BAD_REQUEST, "invalid id");
            };
            Connect::<PollActivity>::new(id)
                .forward(&ctx.env, ACTIVITY_BINDING, req)
                .await
        })
        .get_async("/api/polls/:id", |_req, ctx| async move {
            let Some(id) = route_id(&ctx) else {
                return Response::error("invalid id", 400);
            };
            // Read the head first: the feed lists every vote after it.
            let activity_head = Publisher::<PollActivity>::new(&ctx.env, ACTIVITY_BINDING)?
                .head(&id)
                .await?;
            let tally: Tally = call_poll(&ctx.env, &id, Method::Get, "/tally", None)
                .await?
                .json()
                .await?;
            Response::from_json(&PollSnapshot {
                question: QUESTION.to_owned(),
                options: OPTIONS.iter().map(|o| (*o).to_owned()).collect(),
                tally,
                activity_head,
            })
        })
        .post_async("/api/polls/:id/vote", |mut req, ctx| async move {
            let Some(id) = route_id(&ctx) else {
                return Response::error("invalid id", 400);
            };
            let limiter = ctx.env.rate_limiter("VOTE_LIMITER")?;
            if !limiter.limit(client_ip(&req)).await?.success {
                return Response::error("Too many votes", 429);
            }
            let vote: Vote = match req.json().await {
                Ok(vote) => vote,
                Err(e) => return Response::error(e.to_string(), 400),
            };
            let voter: String = vote.voter.trim().chars().take(MAX_VOTER_LEN).collect();
            if vote.option >= OPTIONS.len() || voter.is_empty() {
                return Response::error("invalid vote", 400);
            }
            let body = serde_json::to_string(&vote).map_err(|e| Error::RustError(e.to_string()))?;
            let tally: Tally = call_poll(&ctx.env, &id, Method::Post, "/vote", Some(body))
                .await?
                .json()
                .await?;
            Publisher::<PollActivity>::new(&ctx.env, ACTIVITY_BINDING)?
                .publish(
                    &id,
                    &ActivityEvent::VoteCast {
                        voter,
                        option: vote.option,
                    },
                )
                .await?;
            Response::from_json(&tally)
        })
        .post_async("/api/polls/:id/reset", |_req, ctx| async move {
            let Some(id) = route_id(&ctx) else {
                return Response::error("invalid id", 400);
            };
            call_poll(&ctx.env, &id, Method::Post, "/reset", None).await
        })
        .run(req, env)
        .await
}
